### ISSUE TITLE
Importing data from 'purple-air' extension

### ISSUE THREAD

**Issue by chrisale** [chaunceygardiner/weewx-purple#1]
Hi there,

This is not directly a question or an issue on your extension but a migration issue. Do you know if your data is 'compatible' with the data in the weewx-purpleair database?  I think I would like to move over to this extension but would be sad to lose the data gathered using the other extension.

Any advice greatly appreciated.
Cheers
Chris

**Comment by chaunceygardiner** [comment]
﻿
Hi Chris,

My extension requires the new extended view schema in WeeWX 4.x.  Assuming you have that, and assuming the interval for that database is the same as your weewx database:

you would need to select the following columns from that purpleair.sdb:
dateTime
pm1_0_atm
pm2_5_atm
pm10_0_atm

Lastly, you would use dateTime to find the correct rows to insert those values into the weewx database.
pm1_0_atm is pm1_0 in weewx.sdb
pm2_5_atm is pm2_5 in weewx.sdb
pm10_0_atm is pm10_0 ink weewx.sdb

A potential problem is that dateTime in the purpleair database might not be on interval boundaries.  It looks like that plugin just uses the current time (which probably means it will be a few seconds off).  As such, you’ll need to fix that before trying to update weewx.sdb.  For example, weewx.sdb might have an archive record at 10:05 today.  The purpleair extension might have its corresponding record at 10:05:03 (that is 3 seconds later).  That 10:05:03 would have to become 10:05.  (And, of course, the column won’t say 10:05, it would be the Unix epoch time corresponding to 10:05 today.)

I can tell you that it was easy for me to move the data into weewx, but I did it from my previous version of my plugin where dateTime was on interval boundaries.

The good news is that you can play with a copy of weewx.sdb while you are tying to get it right.

Cheers,
John

**Comment by chrisale** [comment]
Hi John, 

That's great. Yes I moved to the extended schema when upgrading to Weewx4. I'll take a look at the two dbases now and see if I can import the data in.  I can always backfill so I might do that.

Thanks for your help.

**Comment by chaunceygardiner** [comment]
Backfill is what I am talking about.  You can’t insert the purpleair rows.  You have to fill the pm1_0, pm2_5 and pm10_0 columns in the appropriate (existing) weewx archive record.

And, as mentioned, the column names are different (e.g., pm2_5_atm becomes pm2_5).

Hope this helps.

**Comment by chaunceygardiner** [comment]
Advice provided.  Closing issue.
