### ISSUE TITLE
Feature request: UNBC "corrected" data.

### ISSUE THREAD

**Issue by chrisale** [chaunceygardiner/weewx-purple#2]
Hello again,

This is more of a heads up in terms of research that has been conducted with PurpleAir sensors and high-accuracy (and cost) PM2.5 sensors used by air quality monitoring agencies.

The University of Northern British Columbia has developed formulae that 'correct' the purple air data to be more in line with British Columbia Ministry of Environment PM2.5 sensors.

You can see the result of their work in this map that combines Ministry and PurpleAir sensors across the province with the PA readings being corrected by the formulae:
https://cyclone.unbc.ca/aqmap/v2/index.html?zoom=9&lat=48.878&lng=-124.358

Their formulae have not yet been published in the literature, but they have made them available in the map. (See image)

Their guidance is:
"Apply a correction factor to the PurpleAir (PA) sensors to attempt to make them more similiar to the Agency sensors.

0 - 20 μg m⁻³:
PM₂.₅ = 0.6 x PA + 3.4

20 - 200 μg m⁻³:
PM₂.₅ = 0.6 x PA + 2.5

200+ μg m⁻³:
PM₂.₅ = 1.6 x PA - 194"

My question then is, whether you would be open to adding access to these conversions in your extension?

It could either:
a) create a new database entry for the 'UNBCcorrected' values
b) add an option to convert the PurpleAir readings in the database to these corrected values and store them in place of the raw values.
c) add an option to convert the PurpleAir readings on the fly, leaving the raw PurpleAir values in the database but providing a new variable to weewx to display the 'corrected' values on pages and graphs.

Thanks so much for your consideration.

Cheers
Chris

<img width="618" alt="Screen Shot 2020-09-12 at 08 05 21" src="https://user-images.githubusercontent.com/1987081/92998477-d14ac500-f4ce-11ea-9983-df6ec8c72a62.png">

**Comment by chaunceygardiner** [comment]
I already do this for the lrapa conversion.  I’ve done it with xtypes.  Nothing needs to change in the database.  (BTW, changing the schema would be problematic as the claim is to run with the stock extended schema.)  See my site where I report PM2.5 and AQI both ways: https://www.paloaltoweather.com/

I can add this correction this weekend.  Dose the conversion have a name?  UNBC?

For the lrapa conversion, I use the following:


To show the PM2.5 reading with LRAPA conversion, use the following:

$current.pm2_5_lrapa
To show the Air Quality Index:

$current.pm2_5_lrapa_aqi

How about:


To show the PM2.5 reading with UNBC conversion, use the following:

$current.pm2_5_unbc
To show the Air Quality Index:

$current.pm2_5_unbc_aqi

**Comment by chaunceygardiner** [comment]
BTW, 20 and 200 are repeated.  Which formula should be used for 20?  Which for 200?
Do you have a link to formula?  I’ll need to point to it.

**Comment by chrisale** [comment]
Oh wow you're fast! Those values would be great!  
I only have what they provide at their website. I have been chatting with the scientist who developed though. Dr. Peter Jackson. I would guess that the first block is <20, second block is 20 to <200 and third is >=200 but I will send an email to Peter and point him her and/or respond with his answer.

Oh and the formulas are available only on their website currently:
https://cyclone.unbc.ca/aqmap/v2/index.html

**Comment by chaunceygardiner** [comment]
OK.  I’ve incorporated this conversion into the extension.  You can see it in action at:

https://www.paloaltoweather.com/purple/

Note: The AQI (as opposed to the concentration) is using the US EPA index.  (I could do a Canadian AQI.)

You’ll need to pull at head as I haven’t done a release.  I’d prefer to release after you have confirmed the formula with Dr. Jackson.  Below is what I used.  Note that I treat zero as one to one conversion.  Without this, concentrations cannot be below 3.4 (even when no 2.5 particles are observed).

Please confirm my treatment of a zero concentration and my treatment of 20 and 200 with Dr. Jackson.  Also, it would be really helpful if there is some link I could add that documented the formula.

The exact formula I am using is:

    def compute_pm2_5_unbc(pm2_5):
       if pm2_5 == 0:
            value = pm2_5
        elif pm2_5 <= 20:
            value = 0.6 * pm2_5 + 3.4
        elif pm2_5 <= 200:
            value = 0.6 * pm2_5 + 2.5
        else:
            value = 1.6 * pm2_5 - 194
       return value

**Comment by chrisale** [comment]
This is looking great! The values look like they're corrected now. I have them up on my website www.alberniweather.ca (scroll down until you see the standard almanac layout on the left)

I've put in your question to Dr. Jackson. He did confirm that my breakpoints were correct.

I have a bad max_time/min_time but I'm thinking that might be because the database has not been rebuilt since switching?


High PM2.5
Low PM2.5 
 | 
54.331 μg/m³ at $day.pm2_5_unbc.maxtime
47.826 μg/m³ at $day.pm2_5_unbc.mintime
-- | --

**Comment by chrisale** [comment]
Oh, and if you added the Canadian AQI values, that would be fantastic as it would mean I'd jive with "official" sources up here.

**Comment by chaunceygardiner** [comment]
It’s tricky to implement maxtime and mintime with xtypes as the day summaries that are used don’t have exact times.  As such, I simply use $day.pm_2_5.maxtime and $day.pm2_5_mintime.  These will be the times for $day.pm_2_5_unbc.max and $day.pm_2_5_unbc.min respectively.

**Comment by chaunceygardiner** [comment]
﻿
Hmmm.  I see Canadian sites using the US EPA index.

I do see a Canadian Air Quality Health Index (AQHI).  But Wikipedia tells me that calculation requires NO2 and O3 (in addition to PM2.5).  Of course, PurpleAir provides neither NO2 nor O3.

The formulation of the national AQHI is based on the observed relationship of nitrogen dioxide (NO2), ground-level ozone (O3) and fine particulate matter(PM2.5) with mortality from an analysis of several Canadian cities. Significantly, all three of these pollutants can pose health risks, even at low levels of exposure, especially among those with pre-existing health problems.[4]

Is their a Canadian AQI formula that just needs PM2.5?

**Comment by chrisale** [comment]
You're right, its AQHI that is the unique Canadian item and it requires NO2 and O3. No worries then. This is all great. Thanks so much for your quick work! It's working well.  Now I'll dig into the best way to backfill the database.

**Comment by chaunceygardiner** [comment]
Sounds good.  I’m hoping you can get a more precise formula from Dr. Jackson.  As it is now, it’s funky.  For example, a PM2.5 input of 21 results in a lower adjusted value than an input PM2.5 of 20.  That shouldn’t happen.

Also, sometimes there are rules such as, the input values should be rounded to the nearest int before computing.
