### ISSUE TITLE
How to map 'purple_pressure' 

### ISSUE THREAD

**Issue by mattmon** [chaunceygardiner/weewx-purple#3]
Thanks for making this great plugin!

Is there a way to map 'purple_pressure' to the database?

Some background: 
My setup is using an Acurite Atlas via SDR, which doesn't provide a pressure reading.

Previously, I was been using [purple-air](https://github.com/bakerkj/weewx-purpleair) in combination with [aqi](https://github.com/jonathankoren/weewx-aqi), where aqi configuration allows for me to define `pressure = purple_pressure`.

**Comment by chaunceygardiner** [comment]
Thanks, Matt,

If you literally want the Purple Air’s pressure to be used for pressure, WeeWX has a mechanism to do that.

In weewx.conf:

[StdCalibrate]
   [[Corrections]]                            
        pressure = purple_pressure

**Comment by mattmon** [comment]
That's got me all fixed up; appreciate your quick response!

Thanks again for writing this plugin, keep up the good work :+1:

**Comment by mattmon** [comment]
So, I spoke a little too soon... 

Even with "pressure = purple_pressure" in StdCalibrate -> Corrections, pressure was not being logged to the database.

I added pressure to the loop packet and now all is well.
