### ISSUE TITLE
ERROR: missing module 

### ISSUE THREAD

**Issue by mash55** [chaunceygardiner/weewx-purple#5]
I am trying to get the extension installed on Pi with Bullseye.
Python 3.9.2
weewx 4.5.1

installed extension and configured weewx.conf with my purple air sensor IP address.

Restarted weewx and getting the following error:
Jan 16 17:09:20 weewx python3[3747]: weewx[3747] CRITICAL __main__:     ****    File "/usr/share/weewx/user/purple.py", line 30, in <module>
Jan 16 17:09:20 weewx python3[3747]: weewx[3747] CRITICAL __main__:     ****      from dateutil import tz
Jan 16 17:09:20 weewx python3[3747]: weewx[3747] CRITICAL __main__:     ****  ModuleNotFoundError: No module named 'dateutil'
Jan 16 17:09:20 weewx python3[3747]: weewx[3747] CRITICAL __main__:     ****  Exiting.

Checked for dateutil on my system:
pip3 list | grep date
python-dateutil   2.8.2

Looks like it is installed. Any pointers?

tnx

**Comment by chaunceygardiner** [comment]
Install python3-dateutil.
apt install python3-dateutil

**Comment by mash55** [comment]
tnx for the quick reply - seems to work
