### ISSUE TITLE
Weewx5 in venv needs pip to install requests and dateutils

### ISSUE THREAD

**Issue by n7qnm** [chaunceygardiner/weewx-purple#6]

**Comment by n7qnm** [comment]
Hi - some nits; but when I installed this in weewx 5, I had to use weectl extension install; and I also had to install the two libraries using PIP

**Comment by chaunceygardiner** [comment]
I’ve got WeeWX 5 instructions in 3.9.2.  This is just waiting to hear back from you on whether your other issue is fixed.

**Comment by n7qnm** [comment]
Works great!  

 

Thanks for the quick response and turnaround!

 

Clay

N7QNM

**Comment by chaunceygardiner** [comment]
Fixed in v.3.9.2.
