### ISSUE TITLE
ImportError: cannot import name 'ParserError' from 'dateutil.parser' 

### ISSUE THREAD

**Issue by splobsterman** [chaunceygardiner/weewx-purple#8]
Does anyone else have this error running purple-master under Python3?

[https://github.com/chaunceygardiner/weewx-purple](url)

NUC5
WeeWx 4.10.2

I purged and reinstalled python3-dateutil

Python3 version is 3.7

> Jun 19 20:47:52 NUC62 weewx[5224] CRITICAL __main__: Caught unrecoverable exception:
Jun 19 20:47:52 NUC62 weewx[5224] CRITICAL __main__:     ****  cannot import name 'ParserError' from 'dateutil.parser' (/usr/lib/python3/dist-packages/dateutil/parser/__init__.py)
Jun 19 20:47:52 NUC62 weewx[5224] CRITICAL __main__:     ****  Traceback (most recent call last):
Jun 19 20:47:52 NUC62 weewx[5224] CRITICAL __main__:     ****    File "/home/weewx/bin/weewxd", line 148, in main
Jun 19 20:47:52 NUC62 weewx[5224] CRITICAL __main__:     ****      engine = weewx.engine.StdEngine(config_dict)
Jun 19 20:47:52 NUC62 weewx[5224] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 93, in __init__
Jun 19 20:47:52 NUC62 weewx[5224] CRITICAL __main__:     ****      self.loadServices(config_dict)
Jun 19 20:47:52 NUC62 weewx[5224] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 161, in loadServices
Jun 19 20:47:52 NUC62 weewx[5224] CRITICAL __main__:     ****      obj = weeutil.weeutil.get_object(svc)(self, config_dict)
Jun 19 20:47:52 NUC62 weewx[5224] CRITICAL __main__:     ****    File "/home/weewx/bin/weeutil/weeutil.py", line 1335, in get_object
Jun 19 20:47:52 NUC62 weewx[5224] CRITICAL __main__:     ****      mod = __import__(module)
Jun 19 20:47:52 NUC62 weewx[5224] CRITICAL __main__:     ****    File "/home/weewx/bin/user/purple.py", line 32, in <module>
Jun 19 20:47:52 NUC62 weewx[5224] CRITICAL __main__:     ****      from dateutil.parser import ParserError
Jun 19 20:47:52 NUC62 weewx[5224] CRITICAL __main__:     ****  ImportError: cannot import name 'ParserError' from 'dateutil.parser' (/usr/lib/python3/dist-packages/dateutil/parser/__init__.py)

**Comment by chaunceygardiner** [comment]
Start python3 from the command line.  You should be able to do that by typing python3.
Enter the following line:
from dateutil.parser import ParserError

Do you see the error?  Until you get this to work, there is not point in going any further.
What OS are you using?
Have you updated it?  If not, would you do that and try the above again?

**Comment by splobsterman** [comment]
On Wed, 19 Jun 2024 19:20:42 -0700
John Kline ***@***.*** ***@***.***>> wrote:

> Start python3 from the command line.  You should be able to do that
> by typing python3. Enter the following line:
> from dateutil.parser import ParserError
> 
> Do you see the error?  Until you get this to work, there is not point
> in going any further. What OS are you using?
> Have you updated it?  If not, would you do that and try the above
> again?
> 
> 

John,

I purged python3-dateutils and reinstalled:

***@***.***:/home/weewx $ sudo apt-get install python3-dateutil
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  firmware-microbit-micropython fonts-inconsolata libjs-jquery-ui libqt5charts5 libqt5designer5 libqt5help5 libqt5serialport5 pyflakes pyflakes3 python-matplotlib-data
  python-pyflakes python3-appdirs python3-cycler python3-decorator python3-guizero python3-ipython python3-ipython-genutils python3-jupyter-core python3-kiwisolver
  python3-nudatus python3-pickleshare python3-prompt-toolkit python3-pycodestyle python3-pyflakes python3-pyparsing python3-pyqt5 python3-pyqt5.qsci python3-pyqt5.qtchart
  python3-pyqt5.qtserialport python3-pyqt5.qtsvg python3-semver python3-simplegeneric python3-sip python3-tornado python3-traitlets python3-uflash python3-wcwidth python3-zmq
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  python3-dateutil
0 upgraded, 1 newly installed, 0 to remove and 3 not upgraded.
Need to get 64.5 kB of archives.
After this operation, 317 kB of additional disk space will be used.
Get:1 http://ftp.debian.org/debian buster/main i386 python3-dateutil all 2.7.3-3 [64.5 kB]
Fetched 64.5 kB in 0s (199 kB/s)      
Selecting previously unselected package python3-dateutil.
(Reading database ... 179980 files and directories currently installed.)
Preparing to unpack .../python3-dateutil_2.7.3-3_all.deb ...
Unpacking python3-dateutil (2.7.3-3) ...
Setting up python3-dateutil (2.7.3-3) .

------------------------------------------------------------------

***@***.***:/home/weewx $ python3
Python 3.7.3 (default, Mar 23 2024, 16:12:05) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dateutil.parser import ParserError
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'ParserError' from
'dateutil.parser' (/usr/lib/python3/dist-packages/dateutil/parser/__init__.py)

OS is Raspberry Desktop (Debian 10 Buster) running on an Intel NUC 5

Just ran update && upgrade:

***@***.***:/home/weewx $ python3
Python 3.7.3 (default, Mar 23 2024, 16:12:05) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dateutil.parser import ParserError
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'ParserError' from 'dateutil.parser' (/usr/lib/python3/dist-packages/dateutil/parser/__init__.py)

**Comment by chaunceygardiner** [comment]
Well, in that case, it simply won’t work on Debian 10 Buster.  End of life for Buster is in 11 days (June 30), so it doesn’t make sense to me to get this working.

**Comment by chaunceygardiner** [comment]
Closing for report on a now EOL operating system.
