### ISSUE TITLE
Color incorrect at thresholds -more data

### ISSUE THREAD

**Issue by n7qnm** [chaunceygardiner/weewx-purple#9]
Hi - not 100% sure what's going on; this does seem repeatable - when our air quality gets between 49 and 51, either rising or falling, the aqi-color gets messed up. For example, a few loops ago, the quality is reading 51 and the color is 11195562.666666666, which works out to something between purple and green. A few before that and 49, it was magenta. The current loop is 10079283.2, a lighter purple,

Once it gets above 51, or below 49 it seems to settle out.

**Comment by chaunceygardiner** [comment]
The purple air device itself goes through gradual transitions, but this extension does not.  Rather, it has hard cut-offs.  Here is the code:
    @staticmethod
    def compute_pm2_5_aqi_color(pm2_5_aqi):
        if pm2_5_aqi <= 50:
            return 128 << 8                 # Green
        elif pm2_5_aqi <= 100:
            return (255 << 16) + (255 << 8) # Yellow
        elif pm2_5_aqi <=  150:
            return (255 << 16) + (140 << 8) # Orange
        elif pm2_5_aqi <= 200:
            return 255 << 16                # Red
        elif pm2_5_aqi <= 300:
            return (128 << 16) + 128        # Purple
        else:
            return 128 << 16                # Maroon

The README shows how to get the RGB values:
#set $color = int($current.pm2_5_aqi_color.raw)
#set $blue  =  $color & 255
#set $green = ($color >> 8) & 255
#set $red   = ($color >> 16) & 255

How are you getting the color?  What are the actual RGB values?  What version of this extension are you using?

**Comment by chaunceygardiner** [comment]
Closing because I haven’t heard back.  Please reopen if you want to pursue this further.

**Comment by n7qnm** [comment]
Just checked now, and the aqi_pm2_5_color value was 7474631.111111111.  On the next loop it went back to 16776960.0  - using weewx 5.0.2 and weewx-purple 3.9.2
